name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: pre-commit/action@v3.0.1

  mypy:
    name: Check typing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Load ~/.local cache
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: dotlocal-${{ hashFiles('.github/workflows/ci.yml') }}

      - name: Load virtual environment cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ hashFiles('pyproject.toml', 'poetry.lock') }}

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.8.3'
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv

      - name: Install dependencies
        run: poetry install --only test,homeassistant

      - name: Run mypy
        run: poetry run mypy .

  validate:
    name: Validate for HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands
