name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare release
        run: |
          cd ${{ github.workspace }}/custom_components/device_tracker_template
          zip -r device_tracker_template.zip ./

      - name: Upload zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/device_tracker_template/device_tracker_template.zip
          asset_name: device_tracker_template.zip
          tag: ${{ github.ref }}
          overwrite: true
